# Generated by Django 4.0.2 on 2022-02-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('s_code', models.CharField(blank=True, max_length=10, null=True)),
                ('dept', models.CharField(blank=True, max_length=100, null=True)),
                ('descp', models.TextField(blank=True, null=True)),
                ('prof', models.TextField(blank=True, null=True)),
                ('elec', models.BooleanField(default=False)),
            ],
        ),
    ]
