# Generated by Django 4.0.2 on 2022-02-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('regno', models.IntegerField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
                ('cont', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
