# Generated by Django 4.0.2 on 2022-02-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cont',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(null=True),
        ),
    ]
