# Generated by Django 4.0.2 on 2022-04-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_rename_memberships_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='regno',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
