# Generated by Django 4.0.2 on 2022-04-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_alter_membership_regno_alter_student_regno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='cont',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='regno',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='regno',
        ),
    ]
