# Generated by Django 4.0.2 on 2022-04-24 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registration', '0007_remove_membership_branch_remove_membership_cont_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
